meta_name: "NextDive_"
meta_title: "NextDive_ Find your next spot !"
meta_description: "NextDive_ the place to help you to find your next diving spot ;)"
meta_image: "cover.png" # should exist in `app/assets/images/`
